user nobody nobody;
worker_processes auto;

events
{
  worker_connections 65535;
}

http
{
  include /.AppServiceLauncher/etc/nginx/mime.types;
  default_type application/octet-stream;

  server
  {
    listen 80;

    include /.AppServiceLauncher/etc/nginx/conf.d/chord.conf;

    include /etc/nginx/conf.d/*.conf;
  }
}
